### PR TITLE
Added margins option to DataMatrixWriter & AztecWriter

### PR DESCRIPTION
**Pull request by snail-with-tea**
By default margins = 0 to match previous behavior.
If margins > 0, behavior matches QRCodeWriter margins option.

### CODE REVIEW

**Comment by snail-with-tea** [comment]
Also why DataMatrixWriter removes padding if requested width and height are too small?
QRCodeWriter & AztecWriter do not do that.

**Comment by hschimke** [comment]
> Also why DataMatrixWriter removes padding if requested width and height are too small? QRCodeWriter & AztecWriter do not do that.

The answer is that it was likely how it worked in ZXing and when I ported it over the behavior came too. It isn't an intentional choice on my part.

**Comment by snail-with-tea** [comment]
> The answer is that it was likely how it worked in ZXing and when I ported it over the behavior came too. It isn't an intentional choice on my part.

So backwards compatibility, understandable.

**Review by hschimke — APPROVED** [review]
Change looks good, approved pending test verification

**Comment by hschimke** [comment]
Could you rebase on the latest head commit in the repository? There is an issue with one of my tests that fails which is corrected in the latest commit.

**Comment by snail-with-tea** [comment]
Never done that before. But Github had "Sync fork" button, which seems to do the same.

**Comment by hschimke** [comment]
All tests pass. I'll merge this PR. Thank you for your contribution!

**Comment by hschimke** [comment]
this change is now in v0.6.5 on crates.io

**Pull request merged**
