### PR TITLE
Improve RXingResultPoint usage

### LINKED ISSUE #12: Refactoring RXingResultPoint usage
Since this is a library that works with images, naturally there's a ton of 2D point math going on in the code. I feel like putting in effort here will have a big return on investment, since it's such an integral part of the program logic.

Some points that can be improved in particular:

1. The struct seems to be mostly passed around by reference. This means we end up with dereferences everywhere and the code is harder to follow. The struct itself only holds two floats, so passing it by value would be better I think.
2. Point logic can be refactored in some places to make the intent clearer.
3. Some functions expect rectangles, which are typed as `&[RXingResultPoint]`. A dedicated rectangle type would be better here for type safety.

I'm opening a PR that addresses the first point, and I'd like to tackle points 2 and 3, though that's a more long-term goal.

## Goals

- [ ] Rename `RXingResultPoint` to just `Point`
  - [x] Rename in this repo
  - [ ] Remove references to `RXingResultPoint` and similarly named methods in the `rxing-one-d-proc-derive` crate
- [x] Remove the `MathUtils` module, since it holds duplicated logic
- [x] Remove the `ResultPoint` trait *(all uses in repo removed, but the type still remains because of proc macro)*
- [ ] Remove the `Point` type in the `aztec` module
- [ ] Replace all `f32` parameter pairs and `(f32, f32)` tuples with `Point`
- [ ] Refactor point math code (use `a + b` instead of `let x = a.x + b.x; let y = a.y + b.y`)

### PR DESCRIPTION
**Pull request by Asha20**
Closes #12

### CODE REVIEW

**Comment by Asha20** [comment]
@hschimke I think this might be a good point for a review and maybe a merge if everything looks good. There's still more that can be worked on, but I feel like there's enough improvement here that it's worth merging it and adding more with another PR.

**Comment by hschimke** [comment]
I'll review this evening. For reference: it's just now morning for me.

**Review by hschimke — APPROVED** [review]
Reviewed the code and everything looks good. CI passed.

**Comment by hschimke** [comment]
This looks great, I passed review, I will merge in the morning. Thanks for your hard work!

**Pull request merged**
